
#include <libdrm/drm.h>
#include <stdio.h>

int main()
{
    printf("pub const DRM_IOCTL_VERSION: u32 = %lu;\n", DRM_IOCTL_VERSION);
    printf("pub const DRM_IOCTL_GET_UNIQUE: u32 = %lu;\n", DRM_IOCTL_GET_UNIQUE);
    printf("pub const DRM_IOCTL_GET_MAGIC: u32 = %lu;\n", DRM_IOCTL_GET_MAGIC);
    printf("pub const DRM_IOCTL_IRQ_BUSID: u32 = %lu;\n", DRM_IOCTL_IRQ_BUSID);
    printf("pub const DRM_IOCTL_GET_MAP: u32 = %lu;\n", DRM_IOCTL_GET_MAP);
    printf("pub const DRM_IOCTL_GET_CLIENT: u32 = %lu;\n", DRM_IOCTL_GET_CLIENT);
    printf("pub const DRM_IOCTL_GET_STATS: u32 = %lu;\n", DRM_IOCTL_GET_STATS);
    printf("pub const DRM_IOCTL_SET_VERSION: u32 = %lu;\n", DRM_IOCTL_SET_VERSION);
    printf("pub const DRM_IOCTL_MODESET_CTL: u32 = %lu;\n", DRM_IOCTL_MODESET_CTL);
    printf("pub const DRM_IOCTL_GEM_CLOSE: u32 = %lu;\n", DRM_IOCTL_GEM_CLOSE);
    printf("pub const DRM_IOCTL_GEM_FLINK: u32 = %lu;\n", DRM_IOCTL_GEM_FLINK);
    printf("pub const DRM_IOCTL_GEM_OPEN: u32 = %lu;\n", DRM_IOCTL_GEM_OPEN);
    printf("pub const DRM_IOCTL_GET_CAP: u32 = %lu;\n", DRM_IOCTL_GET_CAP);
    printf("pub const DRM_IOCTL_SET_CLIENT_CAP: u32 = %lu;\n", DRM_IOCTL_SET_CLIENT_CAP);
    printf("\n");
    printf("pub const DRM_IOCTL_SET_UNIQUE: u32 = %lu;\n", DRM_IOCTL_SET_UNIQUE);
    printf("pub const DRM_IOCTL_AUTH_MAGIC: u32 = %lu;\n", DRM_IOCTL_AUTH_MAGIC);
    printf("pub const DRM_IOCTL_BLOCK: u32 = %lu;\n", DRM_IOCTL_BLOCK);
    printf("pub const DRM_IOCTL_UNBLOCK: u32 = %lu;\n", DRM_IOCTL_UNBLOCK);
    printf("pub const DRM_IOCTL_CONTROL: u32 = %lu;\n", DRM_IOCTL_CONTROL);
    printf("pub const DRM_IOCTL_ADD_MAP: u32 = %lu;\n", DRM_IOCTL_ADD_MAP);
    printf("pub const DRM_IOCTL_ADD_BUFS: u32 = %lu;\n", DRM_IOCTL_ADD_BUFS);
    printf("pub const DRM_IOCTL_MARK_BUFS: u32 = %lu;\n", DRM_IOCTL_MARK_BUFS);
    printf("pub const DRM_IOCTL_INFO_BUFS: u32 = %lu;\n", DRM_IOCTL_INFO_BUFS);
    printf("pub const DRM_IOCTL_MAP_BUFS: u32 = %lu;\n", DRM_IOCTL_MAP_BUFS);
    printf("pub const DRM_IOCTL_FREE_BUFS: u32 = %lu;\n", DRM_IOCTL_FREE_BUFS);
    printf("\n");
    printf("pub const DRM_IOCTL_RM_MAP: u32 = %lu;\n", DRM_IOCTL_RM_MAP);
    printf("\n");
    printf("pub const DRM_IOCTL_SET_SAREA_CTX: u32 = %lu;\n", DRM_IOCTL_SET_SAREA_CTX);
    printf("pub const DRM_IOCTL_GET_SAREA_CTX: u32 = %lu;\n", DRM_IOCTL_GET_SAREA_CTX);
    printf("\n");
    printf("pub const DRM_IOCTL_SET_MASTER: u32 = %u;\n", DRM_IOCTL_SET_MASTER);
    printf("pub const DRM_IOCTL_DROP_MASTER: u32 = %u;\n", DRM_IOCTL_DROP_MASTER);
    printf("\n");
    printf("pub const DRM_IOCTL_ADD_CTX: u32 = %lu;\n", DRM_IOCTL_ADD_CTX);
    printf("pub const DRM_IOCTL_RM_CTX: u32 = %lu;\n", DRM_IOCTL_RM_CTX);
    printf("pub const DRM_IOCTL_MOD_CTX: u32 = %lu;\n", DRM_IOCTL_MOD_CTX);
    printf("pub const DRM_IOCTL_GET_CTX: u32 = %lu;\n", DRM_IOCTL_GET_CTX);
    printf("pub const DRM_IOCTL_SWITCH_CTX: u32 = %lu;\n", DRM_IOCTL_SWITCH_CTX);
    printf("pub const DRM_IOCTL_NEW_CTX: u32 = %lu;\n", DRM_IOCTL_NEW_CTX);
    printf("pub const DRM_IOCTL_RES_CTX: u32 = %lu;\n", DRM_IOCTL_RES_CTX);
    printf("pub const DRM_IOCTL_ADD_DRAW: u32 = %lu;\n", DRM_IOCTL_ADD_DRAW);
    printf("pub const DRM_IOCTL_RM_DRAW: u32 = %lu;\n", DRM_IOCTL_RM_DRAW);
    printf("pub const DRM_IOCTL_DMA: u32 = %lu;\n", DRM_IOCTL_DMA);
    printf("pub const DRM_IOCTL_LOCK: u32 = %lu;\n", DRM_IOCTL_LOCK);
    printf("pub const DRM_IOCTL_UNLOCK: u32 = %lu;\n", DRM_IOCTL_UNLOCK);
    printf("pub const DRM_IOCTL_FINISH: u32 = %lu;\n", DRM_IOCTL_FINISH);
    printf("\n");
    printf("pub const DRM_IOCTL_PRIME_HANDLE_TO_FD: u32 = %lu;\n", DRM_IOCTL_PRIME_HANDLE_TO_FD);
    printf("pub const DRM_IOCTL_PRIME_FD_TO_HANDLE: u32 = %lu;\n", DRM_IOCTL_PRIME_FD_TO_HANDLE);
    printf("\n");
    printf("pub const DRM_IOCTL_AGP_ACQUIRE: u32 = %u;\n", DRM_IOCTL_AGP_ACQUIRE);
    printf("pub const DRM_IOCTL_AGP_RELEASE: u32 = %u;\n", DRM_IOCTL_AGP_RELEASE);
    printf("pub const DRM_IOCTL_AGP_ENABLE: u32 = %lu;\n", DRM_IOCTL_AGP_ENABLE);
    printf("pub const DRM_IOCTL_AGP_INFO: u32 = %lu;\n", DRM_IOCTL_AGP_INFO);
    printf("pub const DRM_IOCTL_AGP_ALLOC: u32 = %lu;\n", DRM_IOCTL_AGP_ALLOC);
    printf("pub const DRM_IOCTL_AGP_FREE: u32 = %lu;\n", DRM_IOCTL_AGP_FREE);
    printf("pub const DRM_IOCTL_AGP_BIND: u32 = %lu;\n", DRM_IOCTL_AGP_BIND);
    printf("pub const DRM_IOCTL_AGP_UNBIND: u32 = %lu;\n", DRM_IOCTL_AGP_UNBIND);
    printf("\n");
    printf("pub const DRM_IOCTL_SG_ALLOC: u32 = %lu;\n", DRM_IOCTL_SG_ALLOC);
    printf("pub const DRM_IOCTL_SG_FREE: u32 = %lu;\n", DRM_IOCTL_SG_FREE);
    printf("\n");
    printf("pub const DRM_IOCTL_WAIT_VBLANK: u32 = %lu;\n", DRM_IOCTL_WAIT_VBLANK);
    printf("\n");
    printf("pub const DRM_IOCTL_UPDATE_DRAW: u32 = %lu;\n", DRM_IOCTL_UPDATE_DRAW);
    printf("\n");
    printf("pub const DRM_IOCTL_MODE_GETRESOURCES: u32 = %lu;\n", DRM_IOCTL_MODE_GETRESOURCES);
    printf("pub const DRM_IOCTL_MODE_GETCRTC: u32 = %lu;\n", DRM_IOCTL_MODE_GETCRTC);
    printf("pub const DRM_IOCTL_MODE_SETCRTC: u32 = %lu;\n", DRM_IOCTL_MODE_SETCRTC);
    printf("pub const DRM_IOCTL_MODE_CURSOR: u32 = %lu;\n", DRM_IOCTL_MODE_CURSOR);
    printf("pub const DRM_IOCTL_MODE_GETGAMMA: u32 = %lu;\n", DRM_IOCTL_MODE_GETGAMMA);
    printf("pub const DRM_IOCTL_MODE_SETGAMMA: u32 = %lu;\n", DRM_IOCTL_MODE_SETGAMMA);
    printf("pub const DRM_IOCTL_MODE_GETENCODER: u32 = %lu;\n", DRM_IOCTL_MODE_GETENCODER);
    printf("pub const DRM_IOCTL_MODE_GETCONNECTOR: u32 = %lu;\n", DRM_IOCTL_MODE_GETCONNECTOR);
    printf("pub const DRM_IOCTL_MODE_ATTACHMODE: u32 = %lu;\n", DRM_IOCTL_MODE_ATTACHMODE);
    printf("pub const DRM_IOCTL_MODE_DETACHMODE: u32 = %lu;\n", DRM_IOCTL_MODE_DETACHMODE);
    printf("\n");
    printf("pub const DRM_IOCTL_MODE_GETPROPERTY: u32 = %lu;\n", DRM_IOCTL_MODE_GETPROPERTY);
    printf("pub const DRM_IOCTL_MODE_SETPROPERTY: u32 = %lu;\n", DRM_IOCTL_MODE_SETPROPERTY);
    printf("pub const DRM_IOCTL_MODE_GETPROPBLOB: u32 = %lu;\n", DRM_IOCTL_MODE_GETPROPBLOB);
    printf("pub const DRM_IOCTL_MODE_GETFB: u32 = %lu;\n", DRM_IOCTL_MODE_GETFB);
    printf("pub const DRM_IOCTL_MODE_ADDFB: u32 = %lu;\n", DRM_IOCTL_MODE_ADDFB);
    printf("pub const DRM_IOCTL_MODE_RMFB: u32 = %lu;\n", DRM_IOCTL_MODE_RMFB);
    printf("pub const DRM_IOCTL_MODE_PAGE_FLIP: u32 = %lu;\n", DRM_IOCTL_MODE_PAGE_FLIP);
    printf("pub const DRM_IOCTL_MODE_DIRTYFB: u32 = %lu;\n", DRM_IOCTL_MODE_DIRTYFB);
    printf("\n");
    printf("pub const DRM_IOCTL_MODE_CREATE_DUMB: u32 = %lu;\n", DRM_IOCTL_MODE_CREATE_DUMB);
    printf("pub const DRM_IOCTL_MODE_MAP_DUMB: u32 = %lu;\n", DRM_IOCTL_MODE_MAP_DUMB);
    printf("pub const DRM_IOCTL_MODE_DESTROY_DUMB: u32 = %lu;\n", DRM_IOCTL_MODE_DESTROY_DUMB);
    printf("pub const DRM_IOCTL_MODE_GETPLANERESOURCES: u32 = %lu;\n", DRM_IOCTL_MODE_GETPLANERESOURCES);
    printf("pub const DRM_IOCTL_MODE_GETPLANE: u32 = %lu;\n", DRM_IOCTL_MODE_GETPLANE);
    printf("pub const DRM_IOCTL_MODE_SETPLANE: u32 = %lu;\n", DRM_IOCTL_MODE_SETPLANE);
    printf("pub const DRM_IOCTL_MODE_ADDFB2: u32 = %lu;\n", DRM_IOCTL_MODE_ADDFB2);
    printf("pub const DRM_IOCTL_MODE_OBJ_GETPROPERTIES: u32 = %lu;\n", DRM_IOCTL_MODE_OBJ_GETPROPERTIES);
    printf("pub const DRM_IOCTL_MODE_OBJ_SETPROPERTY: u32 = %lu;\n", DRM_IOCTL_MODE_OBJ_SETPROPERTY);
    printf("pub const DRM_IOCTL_MODE_CURSOR2: u32 = %lu;\n", DRM_IOCTL_MODE_CURSOR2);
    printf("pub const DRM_IOCTL_MODE_ATOMIC: u32 = %lu;\n", DRM_IOCTL_MODE_ATOMIC);
    printf("pub const DRM_IOCTL_MODE_CREATEPROPBLOB: u32 = %lu;\n", DRM_IOCTL_MODE_CREATEPROPBLOB);
    printf("pub const DRM_IOCTL_MODE_DESTROYPROPBLOB: u32 = %lu;\n", DRM_IOCTL_MODE_DESTROYPROPBLOB);
    return 0;
}
