
#include <libdrm/drm.h>
#include <stdio.h>

int main()
{
    printf("pub const DRM_IOCTL_VERSION: c_ulong = %lu;\n", DRM_IOCTL_VERSION);
    printf("pub const DRM_IOCTL_GET_UNIQUE: c_ulong = %lu;\n", DRM_IOCTL_GET_UNIQUE);
    printf("pub const DRM_IOCTL_GET_MAGIC: c_ulong = %lu;\n", DRM_IOCTL_GET_MAGIC);
    printf("pub const DRM_IOCTL_IRQ_BUSID: c_ulong = %lu;\n", DRM_IOCTL_IRQ_BUSID);
    printf("pub const DRM_IOCTL_GET_MAP: c_ulong = %lu;\n", DRM_IOCTL_GET_MAP);
    printf("pub const DRM_IOCTL_GET_CLIENT: c_ulong = %lu;\n", DRM_IOCTL_GET_CLIENT);
    printf("pub const DRM_IOCTL_GET_STATS: c_ulong = %lu;\n", DRM_IOCTL_GET_STATS);
    printf("pub const DRM_IOCTL_SET_VERSION: c_ulong = %lu;\n", DRM_IOCTL_SET_VERSION);
    printf("pub const DRM_IOCTL_MODESET_CTL: c_ulong = %lu;\n", DRM_IOCTL_MODESET_CTL);
    printf("pub const DRM_IOCTL_GEM_CLOSE: c_ulong = %lu;\n", DRM_IOCTL_GEM_CLOSE);
    printf("pub const DRM_IOCTL_GEM_FLINK: c_ulong = %lu;\n", DRM_IOCTL_GEM_FLINK);
    printf("pub const DRM_IOCTL_GEM_OPEN: c_ulong = %lu;\n", DRM_IOCTL_GEM_OPEN);
    printf("pub const DRM_IOCTL_GET_CAP: c_ulong = %lu;\n", DRM_IOCTL_GET_CAP);
    printf("pub const DRM_IOCTL_SET_CLIENT_CAP: c_ulong = %lu;\n", DRM_IOCTL_SET_CLIENT_CAP);
    printf("\n");
    printf("pub const DRM_IOCTL_SET_UNIQUE: c_ulong = %lu;\n", DRM_IOCTL_SET_UNIQUE);
    printf("pub const DRM_IOCTL_AUTH_MAGIC: c_ulong = %lu;\n", DRM_IOCTL_AUTH_MAGIC);
    printf("pub const DRM_IOCTL_BLOCK: c_ulong = %lu;\n", DRM_IOCTL_BLOCK);
    printf("pub const DRM_IOCTL_UNBLOCK: c_ulong = %lu;\n", DRM_IOCTL_UNBLOCK);
    printf("pub const DRM_IOCTL_CONTROL: c_ulong = %lu;\n", DRM_IOCTL_CONTROL);
    printf("pub const DRM_IOCTL_ADD_MAP: c_ulong = %lu;\n", DRM_IOCTL_ADD_MAP);
    printf("pub const DRM_IOCTL_ADD_BUFS: c_ulong = %lu;\n", DRM_IOCTL_ADD_BUFS);
    printf("pub const DRM_IOCTL_MARK_BUFS: c_ulong = %lu;\n", DRM_IOCTL_MARK_BUFS);
    printf("pub const DRM_IOCTL_INFO_BUFS: c_ulong = %lu;\n", DRM_IOCTL_INFO_BUFS);
    printf("pub const DRM_IOCTL_MAP_BUFS: c_ulong = %lu;\n", DRM_IOCTL_MAP_BUFS);
    printf("pub const DRM_IOCTL_FREE_BUFS: c_ulong = %lu;\n", DRM_IOCTL_FREE_BUFS);
    printf("\n");
    printf("pub const DRM_IOCTL_RM_MAP: c_ulong = %lu;\n", DRM_IOCTL_RM_MAP);
    printf("\n");
    printf("pub const DRM_IOCTL_SET_SAREA_CTX: c_ulong = %lu;\n", DRM_IOCTL_SET_SAREA_CTX);
    printf("pub const DRM_IOCTL_GET_SAREA_CTX: c_ulong = %lu;\n", DRM_IOCTL_GET_SAREA_CTX);
    printf("\n");
    printf("pub const DRM_IOCTL_SET_MASTER: c_ulong = %u;\n", DRM_IOCTL_SET_MASTER);
    printf("pub const DRM_IOCTL_DROP_MASTER: c_ulong = %u;\n", DRM_IOCTL_DROP_MASTER);
    printf("\n");
    printf("pub const DRM_IOCTL_ADD_CTX: c_ulong = %lu;\n", DRM_IOCTL_ADD_CTX);
    printf("pub const DRM_IOCTL_RM_CTX: c_ulong = %lu;\n", DRM_IOCTL_RM_CTX);
    printf("pub const DRM_IOCTL_MOD_CTX: c_ulong = %lu;\n", DRM_IOCTL_MOD_CTX);
    printf("pub const DRM_IOCTL_GET_CTX: c_ulong = %lu;\n", DRM_IOCTL_GET_CTX);
    printf("pub const DRM_IOCTL_SWITCH_CTX: c_ulong = %lu;\n", DRM_IOCTL_SWITCH_CTX);
    printf("pub const DRM_IOCTL_NEW_CTX: c_ulong = %lu;\n", DRM_IOCTL_NEW_CTX);
    printf("pub const DRM_IOCTL_RES_CTX: c_ulong = %lu;\n", DRM_IOCTL_RES_CTX);
    printf("pub const DRM_IOCTL_ADD_DRAW: c_ulong = %lu;\n", DRM_IOCTL_ADD_DRAW);
    printf("pub const DRM_IOCTL_RM_DRAW: c_ulong = %lu;\n", DRM_IOCTL_RM_DRAW);
    printf("pub const DRM_IOCTL_DMA: c_ulong = %lu;\n", DRM_IOCTL_DMA);
    printf("pub const DRM_IOCTL_LOCK: c_ulong = %lu;\n", DRM_IOCTL_LOCK);
    printf("pub const DRM_IOCTL_UNLOCK: c_ulong = %lu;\n", DRM_IOCTL_UNLOCK);
    printf("pub const DRM_IOCTL_FINISH: c_ulong = %lu;\n", DRM_IOCTL_FINISH);
    printf("\n");
    printf("pub const DRM_IOCTL_PRIME_HANDLE_TO_FD: c_ulong = %lu;\n", DRM_IOCTL_PRIME_HANDLE_TO_FD);
    printf("pub const DRM_IOCTL_PRIME_FD_TO_HANDLE: c_ulong = %lu;\n", DRM_IOCTL_PRIME_FD_TO_HANDLE);
    printf("\n");
    printf("pub const DRM_IOCTL_AGP_ACQUIRE: c_ulong = %u;\n", DRM_IOCTL_AGP_ACQUIRE);
    printf("pub const DRM_IOCTL_AGP_RELEASE: c_ulong = %u;\n", DRM_IOCTL_AGP_RELEASE);
    printf("pub const DRM_IOCTL_AGP_ENABLE: c_ulong = %lu;\n", DRM_IOCTL_AGP_ENABLE);
    printf("pub const DRM_IOCTL_AGP_INFO: c_ulong = %lu;\n", DRM_IOCTL_AGP_INFO);
    printf("pub const DRM_IOCTL_AGP_ALLOC: c_ulong = %lu;\n", DRM_IOCTL_AGP_ALLOC);
    printf("pub const DRM_IOCTL_AGP_FREE: c_ulong = %lu;\n", DRM_IOCTL_AGP_FREE);
    printf("pub const DRM_IOCTL_AGP_BIND: c_ulong = %lu;\n", DRM_IOCTL_AGP_BIND);
    printf("pub const DRM_IOCTL_AGP_UNBIND: c_ulong = %lu;\n", DRM_IOCTL_AGP_UNBIND);
    printf("\n");
    printf("pub const DRM_IOCTL_SG_ALLOC: c_ulong = %lu;\n", DRM_IOCTL_SG_ALLOC);
    printf("pub const DRM_IOCTL_SG_FREE: c_ulong = %lu;\n", DRM_IOCTL_SG_FREE);
    printf("\n");
    printf("pub const DRM_IOCTL_WAIT_VBLANK: c_ulong = %lu;\n", DRM_IOCTL_WAIT_VBLANK);
    printf("\n");
    printf("pub const DRM_IOCTL_UPDATE_DRAW: c_ulong = %lu;\n", DRM_IOCTL_UPDATE_DRAW);
    printf("\n");
    printf("pub const DRM_IOCTL_MODE_GETRESOURCES: c_ulong = %lu;\n", DRM_IOCTL_MODE_GETRESOURCES);
    printf("pub const DRM_IOCTL_MODE_GETCRTC: c_ulong = %lu;\n", DRM_IOCTL_MODE_GETCRTC);
    printf("pub const DRM_IOCTL_MODE_SETCRTC: c_ulong = %lu;\n", DRM_IOCTL_MODE_SETCRTC);
    printf("pub const DRM_IOCTL_MODE_CURSOR: c_ulong = %lu;\n", DRM_IOCTL_MODE_CURSOR);
    printf("pub const DRM_IOCTL_MODE_GETGAMMA: c_ulong = %lu;\n", DRM_IOCTL_MODE_GETGAMMA);
    printf("pub const DRM_IOCTL_MODE_SETGAMMA: c_ulong = %lu;\n", DRM_IOCTL_MODE_SETGAMMA);
    printf("pub const DRM_IOCTL_MODE_GETENCODER: c_ulong = %lu;\n", DRM_IOCTL_MODE_GETENCODER);
    printf("pub const DRM_IOCTL_MODE_GETCONNECTOR: c_ulong = %lu;\n", DRM_IOCTL_MODE_GETCONNECTOR);
    printf("pub const DRM_IOCTL_MODE_ATTACHMODE: c_ulong = %lu;\n", DRM_IOCTL_MODE_ATTACHMODE);
    printf("pub const DRM_IOCTL_MODE_DETACHMODE: c_ulong = %lu;\n", DRM_IOCTL_MODE_DETACHMODE);
    printf("\n");
    printf("pub const DRM_IOCTL_MODE_GETPROPERTY: c_ulong = %lu;\n", DRM_IOCTL_MODE_GETPROPERTY);
    printf("pub const DRM_IOCTL_MODE_SETPROPERTY: c_ulong = %lu;\n", DRM_IOCTL_MODE_SETPROPERTY);
    printf("pub const DRM_IOCTL_MODE_GETPROPBLOB: c_ulong = %lu;\n", DRM_IOCTL_MODE_GETPROPBLOB);
    printf("pub const DRM_IOCTL_MODE_GETFB: c_ulong = %lu;\n", DRM_IOCTL_MODE_GETFB);
    printf("pub const DRM_IOCTL_MODE_ADDFB: c_ulong = %lu;\n", DRM_IOCTL_MODE_ADDFB);
    printf("pub const DRM_IOCTL_MODE_RMFB: c_ulong = %lu;\n", DRM_IOCTL_MODE_RMFB);
    printf("pub const DRM_IOCTL_MODE_PAGE_FLIP: c_ulong = %lu;\n", DRM_IOCTL_MODE_PAGE_FLIP);
    printf("pub const DRM_IOCTL_MODE_DIRTYFB: c_ulong = %lu;\n", DRM_IOCTL_MODE_DIRTYFB);
    printf("\n");
    printf("pub const DRM_IOCTL_MODE_CREATE_DUMB: c_ulong = %lu;\n", DRM_IOCTL_MODE_CREATE_DUMB);
    printf("pub const DRM_IOCTL_MODE_MAP_DUMB: c_ulong = %lu;\n", DRM_IOCTL_MODE_MAP_DUMB);
    printf("pub const DRM_IOCTL_MODE_DESTROY_DUMB: c_ulong = %lu;\n", DRM_IOCTL_MODE_DESTROY_DUMB);
    printf("pub const DRM_IOCTL_MODE_GETPLANERESOURCES: c_ulong = %lu;\n", DRM_IOCTL_MODE_GETPLANERESOURCES);
    printf("pub const DRM_IOCTL_MODE_GETPLANE: c_ulong = %lu;\n", DRM_IOCTL_MODE_GETPLANE);
    printf("pub const DRM_IOCTL_MODE_SETPLANE: c_ulong = %lu;\n", DRM_IOCTL_MODE_SETPLANE);
    printf("pub const DRM_IOCTL_MODE_ADDFB2: c_ulong = %lu;\n", DRM_IOCTL_MODE_ADDFB2);
    printf("pub const DRM_IOCTL_MODE_OBJ_GETPROPERTIES: c_ulong = %lu;\n", DRM_IOCTL_MODE_OBJ_GETPROPERTIES);
    printf("pub const DRM_IOCTL_MODE_OBJ_SETPROPERTY: c_ulong = %lu;\n", DRM_IOCTL_MODE_OBJ_SETPROPERTY);
    printf("pub const DRM_IOCTL_MODE_CURSOR2: c_ulong = %lu;\n", DRM_IOCTL_MODE_CURSOR2);
    printf("pub const DRM_IOCTL_MODE_ATOMIC: c_ulong = %lu;\n", DRM_IOCTL_MODE_ATOMIC);
    printf("pub const DRM_IOCTL_MODE_CREATEPROPBLOB: c_ulong = %lu;\n", DRM_IOCTL_MODE_CREATEPROPBLOB);
    printf("pub const DRM_IOCTL_MODE_DESTROYPROPBLOB: c_ulong = %lu;\n", DRM_IOCTL_MODE_DESTROYPROPBLOB);
    return 0;
}
